pipeline {
    agent any

    tools {
        maven "M3"
    }
    environment {
            SUITE = "src/test/resources/suites/allTests.xml"
        }

    stages {
        stage('Build') {
            steps {
                git url: 'https://github.com/aliceinwndrlnd/AppiumExampleProject.git'
                bat 'mvn -f AppiumExampleProject/pom.xml clean install'}}
        stage('Test run') {
            steps {
                echo "---------------------------------------------Started src/test/resources/suites/allTests.xml -----------------------------------------------------"
                bat 'mvn test -Dsuite=src/test/resources/suites/allTests.xml'}}
        stage('Reports') {
                steps {
                    script {
                        allure([
                            includeProperties: false,
                            jdk: '',
                            properties: [],
                            reportBuildPolicy: 'ALWAYS',
                            results: [[path: 'target/allure-results']]
                        ])}
                   }
           }
        }
    }
